const fs = require('fs');
let changed = 0, skipped = 0;
function patch(file, oldStr, newStr, label, checkStr) {
  if (!fs.existsSync(file)) { console.log('  SKIP(no file):', file); skipped++; return; }
  let c = fs.readFileSync(file, 'utf8');
  var marker = checkStr || newStr.substring(newStr.length - 60);
  if (c.includes(marker)) { console.log('  SKIP(already):', label); skipped++; return; }
  if (!c.includes(oldStr)) { console.log('  SKIP(no anchor):', label); skipped++; return; }
  c = c.replace(oldStr, newStr);
  fs.writeFileSync(file, c, 'utf8');
  console.log('  OK:', label);
  changed++;
}

// === 1. openScene: add incModuleUsage ===
patch('frontend/app.js',
  "function openScene(id){\n  curScene=id;\n  editId = null;\n  var s=",
  "function openScene(id){\n  curScene=id;\n  editId = null;\n  incModuleUsage(id);\n  var s=",
  'openScene+incModuleUsage');

// === 2. Add MODULE_USAGE functions before MODULE_META ===
patch('frontend/app.js',
  "var MODULE_META = {\n  body:{name:'\u8eab\u4f53'",
  "var MODULE_USAGE_KEY = 'qiezi_module_usage_v1';\nfunction getModuleUsage(){try{return JSON.parse(localStorage.getItem(MODULE_USAGE_KEY)||'{}')}catch(e){return{}}}\nfunction incModuleUsage(mid){var u=getModuleUsage();u[mid]=(u[mid]||0)+1;u[mid+'_last']=Date.now();try{localStorage.setItem(MODULE_USAGE_KEY,JSON.stringify(u))}catch(e){}}\nfunction getTopModules(n){var u=getModuleUsage();var s={};Object.keys(u).forEach(function(k){if(k.endsWith('_last'))return;s[k]=u[k]});return Object.entries(s).sort(function(a,b){return b[1]-a[1]}).slice(0,n).map(function(x){return x[0]})}\n\nvar MODULE_META = {\n  body:{name:'\u8eab\u4f53'",
  'MODULE_USAGE functions');

// === 3. renderRecord: add favorites ===
patch('frontend/app.js',
  "function renderRecord(){\n  // \u4eca\u65e5\u7edf\u8ba1\n  renderRecToday();\n  // \u5206\u7ec4\u6e32\u67d3\n  Object.keys(RECORD_GROUPS).forEach(function(cat){",
  "function renderRecord(){\n  renderRecToday();\n  var topMods = getTopModules(6);\n  if (topMods.length > 0) {\n    var favEl = document.getElementById('recFavorites');\n    if (!favEl) {\n      favEl = document.createElement('div');\n      favEl.className = 'rec-group';\n      favEl.innerHTML = '<div class=\"rg-title\">\u2b50 \u5e38\u7528\u573a\u666f <span class=\"rg-sub\">\u6309\u4f7f\u7528\u9891\u7387\u81ea\u52a8\u6392\u5e8f</span></div><div class=\"scene-grid rec-grid\" id=\"recFavGrid\"></div>';\n      var recToday = document.getElementById('recToday');\n      if (recToday && recToday.parentNode) recToday.parentNode.insertBefore(favEl, recToday.nextSibling);\n    }\n    favEl.style.display = '';\n    var grid = document.getElementById('recFavGrid');\n    if (grid) grid.innerHTML = topMods.map(function(mid){ return renderSceneCard(mid, true); }).join('');\n  }\n  Object.keys(RECORD_GROUPS).forEach(function(cat){",
  'renderRecord+favorites');

// === 4. renderSceneCard: add featured param ===
patch('frontend/app.js',
  "function renderSceneCard(mid){\n  var meta = MODULE_META[mid] || {name:mid, icon:'\ud83d\udcc4'};\n  var cnt = (dataCache[mid]||[]).length;\n  var todayCnt = countTodayRecords(mid);\n  var todayBadge = todayCnt > 0 ? '<div class=\"s-today\">'+todayCnt+'</div>' : '';\n  return '<div class=\"scene-card\" data-name=\"'+meta.name+'\" onclick=\"openScene(\\''+mid+'\\')\"><div class=\"s-ic\">'+meta.icon+'</div><div class=\"s-nm\">'+meta.name+'</div><div class=\"s-cnt\">'+cnt+'\u6761</div>'+todayBadge+'</div>';\n}",
  "function renderSceneCard(mid, featured){\n  var meta = MODULE_META[mid] || {name:mid, icon:'\ud83d\udcc4'};\n  var cnt = (dataCache[mid]||[]).length;\n  var todayCnt = countTodayRecords(mid);\n  var todayBadge = todayCnt > 0 ? '<div class=\"s-today\">'+todayCnt+'</div>' : '';\n  var featBadge = featured ? '<div style=\"position:absolute;top:4px;right:4px;font-size:10px;color:var(--c-primary);\">\u2b50</div>' : '';\n  return '<div class=\"scene-card'+(featured?' scene-featured':'')+'\" data-name=\"'+meta.name+'\" onclick=\"openScene(\\''+mid+'\\')\" style=\"position:relative;\">'+featBadge+'<div class=\"s-ic\">'+meta.icon+'</div><div class=\"s-nm\">'+meta.name+'</div><div class=\"s-cnt\">'+cnt+'\u6761</div>'+todayBadge+'</div>';\n}",
  'renderSceneCard+featured', 'featBadge');

// === 5. renderOverview: add sparkline + collapseZeroData ===
patch('frontend/app.js',
  "function renderOverview(){\n  var sleep = dataCache.sleep || [], emotion = dataCache.emotion || [];\n  var sl=0, em=0;\n  sleep.slice(-7).forEach(function(s){ sl += parseFloat(s.hours) || 0; });\n  emotion.slice(-7).forEach(function(e){ em += parseFloat(e.rating) || 0; });\n  document.getElementById('ovSleep').textContent = (sleep.length ? (sl/Math.min(7,sleep.length)).toFixed(1) : '-') + 'h';\n  document.getElementById('ovMood').textContent = (emotion.length ? (em/Math.min(7,emotion.length)).toFixed(1) : '-') + '/10';\n  document.getElementById('ovDays').textContent = Math.max(sleep.length, emotion.length, 1);\n}",
  "function renderOverview(){\n  var sleep = dataCache.sleep || [], emotion = dataCache.emotion || [];\n  var sl=0, em=0;\n  var sleepRecent = sleep.slice(-7);\n  var emotionRecent = emotion.slice(-7);\n  sleepRecent.forEach(function(s){ sl += parseFloat(s.hours) || 0; });\n  emotionRecent.forEach(function(e){ em += parseFloat(e.rating) || 0; });\n  var ovSleep = document.getElementById('ovSleep');\n  var ovMood = document.getElementById('ovMood');\n  var ovDays = document.getElementById('ovDays');\n  if (ovSleep) { var sa = sleep.length ? (sl/Math.min(7,sleep.length)).toFixed(1) : '-'; ovSleep.innerHTML = sa + 'h' + buildSparkline(sleepRecent, 'hours'); }\n  if (ovMood) { var ma = emotion.length ? (em/Math.min(7,emotion.length)).toFixed(1) : '-'; ovMood.innerHTML = ma + '/10' + buildSparkline(emotionRecent, 'rating'); }\n  if (ovDays) ovDays.textContent = Math.max(sleep.length, emotion.length, 1);\n  if (typeof collapseZeroData === 'function') collapseZeroData();\n}\nfunction collapseZeroData(){\n  if (!dataCache) return;\n  var allEmpty = true;\n  Object.keys(dataCache).forEach(function(k){ if (Array.isArray(dataCache[k]) && dataCache[k].length > 0) allEmpty = false; });\n  if (!allEmpty) return;\n  document.querySelectorAll('.tool-section').forEach(function(sec){\n    var items = sec.querySelectorAll('.tool-item');\n    var visibleCount = 0;\n    items.forEach(function(item){ var cntEl = item.querySelector('.t-cnt'); var cnt = cntEl ? cntEl.textContent : ''; if (cnt && cnt !== '0' && cnt !== '-' && cnt !== '\u672a\u8bbe' && cnt !== '\u672a\u7acb' && cnt !== '\u65b0') visibleCount++; });\n    if (visibleCount === 0 && items.length > 3) sec.style.opacity = '0.4';\n  });\n}\nfunction buildSparkline(data, field){\n  if (!data || data.length < 2) return '';\n  var values = data.map(function(d){ return parseFloat(d[field]) || 0; });\n  if (values.every(function(v){ return v === 0; })) return '';\n  var w = 40, h = 14, pad = 2;\n  var min = Math.min.apply(null, values); var max = Math.max.apply(null, values); var range = max - min || 1;\n  var points = values.map(function(v, i){ var x = pad + (i / (values.length - 1)) * (w - 2*pad); var y = pad + (1 - (v - min) / range) * (h - 2*pad); return x.toFixed(1) + ',' + y.toFixed(1); }).join(' ');\n  var color = values[values.length-1] >= values[0] ? '#10B981' : '#EF4444';\n  return '<svg width=\"'+w+'\" height=\"'+h+'\" style=\"vertical-align:middle;margin-left:4px;\"><polyline points=\"'+points+'\" fill=\"none\" stroke=\"'+color+'\" stroke-width=\"1.5\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/></svg>';\n}",
  'renderOverview+sparkline+collapse', 'buildSparkline');

// === 6. submitDailyAnswer: merge flash notes ===
patch('frontend/app.js',
  "async function submitDailyAnswer() {\n  var inp = document.getElementById('dailyQuestionInput');\n  if (!inp) return;\n  var ans = inp.value.trim();\n  if (!ans) { alert('\u8bf7\u5148\u5199\u4e0b\u4f60\u7684\u56de\u7b54'); return; }\n  try {\n    var today = new Date().toISOString().split('T')[0];\n    var r = await fetch('/api/daily-question/answer', {\n      method: 'POST',\n      headers: { 'Content-Type': 'application/json' },\n      body: JSON.stringify({ answer: ans, date: today })\n    });\n    var d = await r.json();\n    if (d.success) {\n      alert('\u2705 \u56de\u7b54\u5df2\u4fdd\u5b58\uff01\u6df1\u5ea6\u8bc4\u5206\uff1a' + d.depthScore + '/5');\n      loadDailyQuestion();\n      if (typeof renderOverview === 'function') renderOverview();\n    } else {\n      alert('\u4fdd\u5b58\u5931\u8d25\uff1a' + d.message);\n    }\n  } catch(e) { alert('\u7f51\u7edc\u9519\u8bef\uff0c\u8bf7\u91cd\u8bd5'); }\n}",
  "async function submitDailyAnswer() {\n  var inp = document.getElementById('dailyQuestionInput');\n  if (!inp) return;\n  var ans = inp.value.trim();\n  if (!ans) { alert('\u8bf7\u5148\u5199\u4e0b\u4f60\u7684\u60f3\u6cd5'); return; }\n  var today = new Date().toISOString().split('T')[0];\n  var qEl = document.getElementById('dailyQuestionText');\n  var hasQuestion = qEl && qEl.textContent && qEl.textContent.trim().length > 0;\n  var isQuickNote = !hasQuestion || ans.length < 5;\n  try {\n    if (isQuickNote) {\n      var r2 = await fetch('/api/quick-note', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: ans }) });\n      var d2 = await r2.json();\n      if (d2.success) {\n        var fb = document.getElementById('quickNoteFeedback');\n        if (fb) fb.innerHTML = '\u2705 \u5df2\u81ea\u52a8\u5f52\u7c7b\u5230 <b>'+ (d2.module || '\u95ea\u5ff5') + '</b>';\n        inp.value = '';\n        setTimeout(function(){ if(fb) fb.innerHTML = ''; }, 3000);\n      } else { alert('\u4fdd\u5b58\u5931\u8d25\uff1a' + d2.message); }\n    } else {\n      var r = await fetch('/api/daily-question/answer', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ answer: ans, date: today }) });\n      var d = await r.json();\n      if (d.success) {\n        alert('\u2705 \u56de\u7b54\u5df2\u4fdd\u5b58\uff01\u6df1\u5ea6\u8bc4\u5206\uff1a' + d.depthScore + '/5');\n        loadDailyQuestion();\n        if (typeof renderOverview === 'function') renderOverview();\n      } else { alert('\u4fdd\u5b58\u5931\u8d25\uff1a' + d.message); }\n    }\n  } catch(e) { alert('\u7f51\u7edc\u9519\u8bef\uff0c\u8bf7\u91cd\u8bd5'); }\n}",
  'submitDailyAnswer+merge', 'isQuickNote');

// === 7. dashboard: add weeklyReview/dataCompare rendering ===
patch('frontend/app.js',
  "  // v6.5.9 \u5468\u5bf9\u5468/\u6708\u5bf9\u6708\u6570\u636e\u5bf9\u6bd4\u56fe\n  html += renderTrendComparison();",
  "  // v6.9.21: weeklyReview + dataCompare\n  if(s.weeklyReview){\n    var wr = s.weeklyReview;\n    html += '<div style=\"background:var(--c-surface);border-radius:14px;padding:12px 16px;margin-bottom:12px;\">';\n    html += '<div style=\"display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;\"><span style=\"font-size:12px;font-weight:600;color:var(--c-fg-2);\">\ud83d\udcc5 \u5468\u56de\u987e</span><span style=\"font-size:11px;color:var(--c-fg-3);\">'+wr.period+'</span></div>';\n    if(wr.summary) html += '<div style=\"font-size:12px;color:var(--c-fg);line-height:1.5;margin-bottom:6px;\">'+escapeHtml(wr.summary)+'</div>';\n    if(wr.changes && wr.changes.length){ wr.changes.forEach(function(c){ var ar = c.direction === 'up' ? '\u2191' : '\u2193'; var co = c.direction === 'up' ? 'var(--c-success)' : 'var(--c-danger)'; html += '<div style=\"font-size:11px;color:var(--c-fg-2);padding:2px 0;\"><span style=\"color:'+co+';\">'+ar+'</span> '+escapeHtml(c.dim)+' '+escapeHtml(c.delta)+' <span style=\"color:var(--c-fg-3);\">'+escapeHtml(c.note||'')+'</span></div>'; }); }\n    if(wr.highlights) html += '<div style=\"font-size:11px;color:var(--c-fg-3);margin-top:4px;font-style:italic;\">'+escapeHtml(wr.highlights)+'</div>';\n    html += '</div>';\n  }\n  if(s.dataCompare){\n    var dc = s.dataCompare;\n    if(dc.week && dc.week.diffs && dc.week.diffs.length){\n      html += '<div style=\"background:var(--c-surface);border-radius:14px;padding:12px 16px;margin-bottom:12px;\">';\n      html += '<div style=\"font-size:12px;font-weight:600;color:var(--c-fg-2);margin-bottom:6px;\">\ud83d\udcca \u5468\u5bf9\u6bd4</div>';\n      dc.week.diffs.forEach(function(d){ var ar = d.direction === 'up' ? '\u2191' : '\u2193'; var co = d.direction === 'up' ? 'var(--c-success)' : 'var(--c-danger)'; html += '<div style=\"display:flex;justify-content:space-between;font-size:11px;padding:2px 0;\"><span style=\"color:var(--c-fg-2);\">'+escapeHtml(d.label)+'</span><span><span style=\"color:'+co+';\">'+ar+'</span> '+escapeHtml(d.current)+' <span style=\"color:var(--c-fg-3);\">('+(d.pct?d.pct+'%':'')+')</span></span></div>'; });\n      html += '</div>';\n    }\n  }\n  html += renderTrendComparison();",
  'dashboard+weeklyReview/dataCompare');

console.log('\n=== app.js patch done: ' + changed + ' changed, ' + skipped + ' skipped ===');
